version: 2.0

jobs:
    build:
        docker:
            - image: circleci/9-jdk-sid-node-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - gradle-{{ checksum "build.gradle" }}
            - run: ./gradlew assemble
            - run: ./gradlew run
            - run: ./gradlew test
            - run: ./gradlew uploadArchives
            - save_cache:
                paths:
                    - ~/.gradle
                key: gradle-{{ checksum "build.gradle" }}
